.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH brcm_patchram_plus 1 "January 2013" Linux "User Manuals"
.SH NAME
brcm_patchram_plus \- Download HCD file via serial interface.
.br
brcm_patchram_plus_usb \- Download HCD file via USB.
.br
brcm_patchram_plus_h5 \- Download HCD file via either HCI UART (H4) or HCI three-wire UART (H5).
.SH SYNOPSIS
.B brcm_patchram_plus [OPTION]... 
.I [DEVICE NAME]...
.SH DESCRIPTION

This suite of programs programs are used to download a
"patchram" firmware file in the HCD format to Broadcom
Bluetooth based silicon and combo chips as well as other
utility functions.

The main difference between the programs is the transport
mechanism.

.SH OPTIONS

.B Common Options:
.IP -d
Print debug messages.

.IP "--patchram patchram-file"

.IP "--bd_addr bd-address

.B H4/H5 UART Options

.IP "--enable_lpm"
Enable low power mode

.IP "--enable_hci | enable_h4"

The use of either of these parameters will cause the H4 Line
Discipline to be loaded and the port to be kept 
open until the program is terminated.

.IP "--enable_h5"

The use of either of these parameters will cause the H5
(3-Wire) Line Discipline to be loaded and the port to be kept 
open until the program is terminated.

.IP "--use_baudrate_for_download"

.IP "--scopcm=sco_routing,pcm_interface_rate,frame_type, sync_mode,clock_mode,lsb_first,fill_bits, fill_method,fill_num,right_justify"

Where:

sco_routing is 0 for PCM, 1 for Transport,
2 for Codec and 3 for I2S,

pcm_interface_rate is 0 for 128KBps, 1 for
256 KBps, 2 for 512KBps, 3 for 1024KBps,
and 4 for 2048Kbps,

frame_type is 0 for short and 1 for long,

sync_mode is 0 for slave and 1 for master,

clock_mode is 0 for slabe and 1 for master,

lsb_first is 0 for false aand 1 for true,

fill_bits is the value in decimal for unused bits,

fill_method is 0 for 0's and 1 for 1's, 2 for signed and 3 for programmable,

fill_num is the number or bits to fill,

right_justify is 0 for false and 1 for true

Must be set to one of the following values:

.IP "--i2s=i2s_enable,is_master,sample_rate,clock_rate"
Where

i2s_enable is 0 for disable and 1 for enable,

is_master is 0 for slave and 1 for master,

sample_rate is 0 for 8KHz, 1 for 16Khz and 2 for 4 KHz,

clock_rate is 0 for 128KHz, 1 for 256KHz, 3 for 1024 KHz and 4 for 2048 KHz.
.IP "--no2bytes"
Skips waiting for two byte confirmation before starting patchram
download. Newer chips do not generate these two bytes.

.IP "--tosleep=n"
Where
.I n
is the number of microsseconds to sleep before
patchram download begins.

.SH DEVICE NAME
.I 
the name of the UART or USB device.

.SH EXAMPLES

Serial:

brcm_patchram_plus -d --patchram \\
.br
	BCM2045B2_002.002.011.0348.0349.hcd /dev/ttyHS0

USB:

brcm_patchram_plus -d --patchram  \\
.br
	BCM2045B2_002.002.011.0348.0349.hcd hci0

H5:

brcm_patchram_plus -d --enable_h5 --patchram  \\
.br
	BCM2045B2_002.002.011.0348.0349.hcd /dev/ttyHS0

.SH ENVIRONMENT
.SH DIAGNOSTICS
.SH BUGS
.SH AUTHOR
Mark Mendelsohn <mendelso@broadcom.com>
.SH "SEE ALSO"
